# Use root/example como credenciais de usuário/senha
version: '3.1'

services:

  db:
    image: mysql
    # NOTA: O uso de "mysql_native_password" não é recomendado: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (este é apenas um exemplo, não pretende ser uma configuração de produção)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
